export const SET_ORDERID = "SET_ORDERID";
export const SET_ORDER_QUEUE = "SET_ORDER_QUEUE";
export const REMOVE_ORDER = "REMOVE_ORDER";
export const UPDATE_ORDER_STATUS = "UPDATE_ORDER_STATUS";
export const ADD_ORDER = "ADD_ORDER";
